# LIGNES GE-TGE

## LES DONNEES 

- périmètre entité : Urssaf

- les catégories de cotisants Ogur : "TGE", "GE et VLU" 

- Les activités : 
Toutes les activités de service hors Fend, hors accueil téléphonique, hors Trésorerie-gestion R, hors Contrôle, hors contrôle sur pièces 

- **L'output : le nombre de siren (source Sidéral)**

- L'input : le nombre d'ETPP des activités citées (avec encadrement)


- **Le facteur de charge : le nombre moyen de comptes par entreprise**.
Le nombre de comptes : nombre de comptes actifs (source Icare, moyenne des 4 trimestres)

- La mutualisation : pas de correction

## LE CHOIX DES REFERENCES DE PRODUCTIVITE

Le calcul de la référence de productivité repose sur 2 hypothèses issues des connaissances des experts métier :

- L'agent gère une entreprise (et l'ensemble des comptes qui s'y rattachent) et pas seulement un compte. Donc, pour le calcul de la productivité l'Output est le nombre d'entreprises. 


- le nombre moyen de comptes par entreprise est un facteur de charge supplémentaire. Les opérations manuelles de gestion des comptes sont plus chronophages pour les entreprises ayant un plus grand nombre d' établissements


La prise en compte simultanée de ces deux éléments entraine **le choix d'une référence de productivité différenciée (propre à chaque organisme)**. 


La productivité liée au nombre moyen d'établissements par entreprise selon la relation suivante (estimation par régression linéaire) :

**Productivité de référence = " " x Nombre moyen d'établissements**


Les résultats statistiques détaillés sont fournis en annexe



## LE CALCUL DU SPC

Pour une activité du référentiel, le Score des Productivités Comparées se définit comme le rapport entre effectif de référence et l'effectif réel. L'effectif de référence est l'effectif nécessaire pour atteindre la référence de productivité.

Le SPC s'exprime également comme le rapport entre la productivité observée et la productivité de référence.

**SPC = Effectif de référence / Effectif** 

ou 

**Productivité / Référence de produtivité**


Le SPC mesure l'écart à la référence de productivité. Un score proche de la valeur  1 indique un écart à la référence faible, un score supérieur à 1 signifie un niveau de productivité supérieur à la référence. 

Il se décline également en « enjeu en ETP »  : 
**Enjeu Effectif = Effectif - Effectif de référence = Effectif ( 1- SPC)**

Ainsi, un enjeu largement positif correspond à un SPC faible, càd éloigné de la référence de productivité. 


## ANNEXE STAT
